# Generated by Django 4.1.2 on 2022-11-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_dislike_create_user_dislike_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='create_user',
            new_name='created_user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='create_user',
            new_name='created_user',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='create_user',
            new_name='created_user',
        ),
    ]
