# Generated by Django 4.1.2 on 2022-11-10 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0003_rename_create_user_dislike_created_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='author_id',
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('created_user', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('created_user', 'video')},
        ),
        migrations.AlterIndexTogether(
            name='dislike',
            index_together={('created_user', 'video')},
        ),
        migrations.AlterIndexTogether(
            name='like',
            index_together={('created_user', 'video')},
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_id',
        ),
    ]
